package com.cn.xm.pojo;

public class AuthIdentifier {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column auth_identifier.id
     * @mbggenerated
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column auth_identifier.uuid
     * @mbggenerated
     */
    private String uuid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column auth_identifier.type
     * @mbggenerated
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column auth_identifier.code
     * @mbggenerated
     */
    private String code;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column auth_identifier.data
     * @mbggenerated
     */
    private String data;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column auth_identifier.expired
     * @mbggenerated
     */
    private Long expired;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column auth_identifier.id
     * @return  the value of auth_identifier.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column auth_identifier.id
     * @param id  the value for auth_identifier.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column auth_identifier.uuid
     * @return  the value of auth_identifier.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column auth_identifier.uuid
     * @param uuid  the value for auth_identifier.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column auth_identifier.type
     * @return  the value of auth_identifier.type
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column auth_identifier.type
     * @param type  the value for auth_identifier.type
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column auth_identifier.code
     * @return  the value of auth_identifier.code
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column auth_identifier.code
     * @param code  the value for auth_identifier.code
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column auth_identifier.data
     * @return  the value of auth_identifier.data
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column auth_identifier.data
     * @param data  the value for auth_identifier.data
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column auth_identifier.expired
     * @return  the value of auth_identifier.expired
     * @mbggenerated
     */
    public Long getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column auth_identifier.expired
     * @param expired  the value for auth_identifier.expired
     * @mbggenerated
     */
    public void setExpired(Long expired) {
        this.expired = expired;
    }
}