package com.cn.xm.dao;

import com.cn.xm.common.model.AuthUser;

import java.util.Map;

public interface AuthUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    AuthUser selectByPrimaryKey(Long id);
    
    AuthUser selectByUsernameEmail(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthUser record);
    int updateByEmailSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthUser record);
}