package com.cn.xm.dao;

import com.cn.xm.common.model.AuthUser;

public interface AuthUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    AuthUser selectByPrimaryKey(Long id);
    
    AuthUser selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_user
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthUser record);
}