package com.cn.xm.dao;

import com.cn.xm.pojo.AuthIdentifier;

public interface AuthIdentifierMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_identifier
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_identifier
     * @mbggenerated
     */
    int insert(AuthIdentifier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_identifier
     * @mbggenerated
     */
    int insertSelective(AuthIdentifier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_identifier
     * @mbggenerated
     */
    AuthIdentifier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_identifier
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthIdentifier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table auth_identifier
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthIdentifier record);
}